# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4018ffa6201bc177552f1e310fed3b4261203f4151a34817f85e3c371bd891058d569f629073545deb094c4de1a6887ecd0d1a6f578384c8c794d3ca959708a5

test:
  secret_key_base: 9fc573fb9a572ebfd9e59d3b60c5c7dc8bb3d48e60e360761bc33ab7d354001fc1bc75d18b8f7ef1f8f823ff443f62e6c1f4d32acac64dba8feeb0792e982da4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
